### ISSUE TITLE
Complete installation setup in Linux based system 

### ISSUE THREAD

**Issue by gagantous** [gagantous/django-learn#1]
I need someone who can make an installation setup based on inux system

To Do List

1. Installation steps for requirement apps ( such as python, Pip,Virtual Environtment )
2. Make a README.md in my repository

Thanks in advance.

**Comment by ilosaurus** [comment]
ready to fork.

**Comment by gagantous** [comment]
Hi @muhilhams  
Thanks for helping this project grow bigger. I am gonna assign you for this issue.

**Comment by verhagen** [comment]
Is it an idea to create a virtual machine in [VirtualBox](https://www.virtualbox.org)?
This can be done through [Vagrant](https://www.vagrantup.com/) which uses a configuration file `Vagrantfile` through which users then easily can create a virtual machine.

It will make this *Learning Django* tutorial available for everyone as VirtualBox is available for Windows, Linux and OS-X.

**Comment by harishr1308** [comment]
Resolved #2

**Comment by gagantous** [comment]
Hi @harishr1308 !

Thanks for the helpful documentation, i really appreciate it!
